### ISSUE TITLE
Problem in flows

### ISSUE THREAD

**Issue by MartinG72** [sammyjo86/SwedishRedDays#1]
The card give me an red X regardles of config.

**Comment by sammyjo86** [comment]
I have seen this as well but with the old version, I you hold the hand above the red X is there a error message? 

What version are you using? I released a new couple of days ago

**Comment by sammyjo86** [comment]
Issue solved in version 1.0.2, please verify.

**Comment by sammyjo86** [comment]
Version 1.0.2 released to  Athome apps
