### ISSUE TITLE
Homey pro 2023 

### ISSUE THREAD

**Issue by nissenhj** [sammyjo86/SwedishRedDays#10]
Hej!
Kommer du att uppgradera appen så den blir användbar i Homey pro 2023?

**Comment by Kekke14u** [comment]
+1 på den

**Comment by Slarvidsson** [comment]
+1

**Comment by magohl** [comment]
+1

**Comment by niXta1** [comment]
@sammyjo86 har inte varit inne på några år, det ligger en automatisk pull-request som inte accepterats på snart ett år.
Jag gissar att den enda möjligheten är att @JohanBendz förbarmar sig över oss och uppdaterar appen. Jag har dock ingen som helst aning om hur mycket jobb det kräver, även om appen ser enkel ut.

**Comment by sammyjo86** [comment]
Kommer kika på det men varit fullt i kalendern :p

**Comment by niXta1** [comment]
Får HP2023 nästa vecka så behöver du testare så säg till 😊

**Comment by SA0BJW** [comment]
Fått hem min Pro 2023, och avvaktar med att flytta in i den tills denna och ytterligare en app uppdateras då jag har lite för många flöden som är beroende av den här appen!

**Comment by nissenhj** [comment]
> Fått hem min Pro 2023, och avvaktar med att flytta in i den tills denna och ytterligare en app uppdateras då jag har lite för många flöden som är beroende av den här appen!

Jag har denna och ett par appar till som måste fungera i pro 2023 innan jag ens funderar på att beställa en

**Comment by SA0BJW** [comment]
Ledsamt att denna app inte är kompatibel med 2023. Har inte flyttat in i min nya pro i väntan på en uppdatering, men det verkar ju kört. Får skriva om berörda flöden å skippa den här utmätkta app:en.

**Comment by nissenhj** [comment]
> Ledsamt att denna app inte är kompatibel med 2023. Har inte flyttat in i min nya pro i väntan på en uppdatering, men det verkar ju kört. Får skriva om berörda flöden å skippa den här utmätkta app:en.

Du kan alltid använda dig av "Public holidays"
Värre för oss som använder Bofu rullgardiner och är beroende av "Sunway Window Coverings" finns inget alternativ

**Comment by sammyjo86** [comment]
Mycket händer just nu, har i stort en fungerande version med något mindre problem med GlobalTokens. Men snart smäller det nog :)

**Comment by sammyjo86** [comment]
Här är den klar att testa :)

https://homey.app/a/se.faboul.svenskahelgdagar/test/

**Comment by niXta1** [comment]
> Här är den klar att testa :)
> 
> https://homey.app/a/se.faboul.svenskahelgdagar/test/

Äntligen, tack! 🙏🏼
